ImplicitMVC.Core/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using ImplicitMVC.Core.Configuration.Constants;

namespace ImplicitMVC.Core.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Login()
        {
            return RedirectToAction("Index");
        }

        public IActionResult Logout()
        {
            // Signout from your app and xena login provider
            return new SignOutResult(new[] { CookieAuthenticationDefaults.AuthenticationScheme, AuthenticationConstants.XenaOidcAuthenticationScheme });
        }

        public IActionResult LogoutRedirect()
        {
            return View();
        }

        public IActionResult Terms() => View();
    }
}

ImplicitMVC.Core/Controllers/TokenController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ImplicitMVC.Core.Controllers
{
    [Authorize]
    public class TokenController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ImplicitMVC.Core/Controllers/XenaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ImplicitMVC.Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json.Linq;

namespace ImplicitMVC.Core.Controllers
{
    [Authorize]
    public class XenaController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IXenaService _xenaService;

        public XenaController(IConfiguration configuration, IXenaService xenaService)
        {
            _configuration = configuration;
            _xenaService = xenaService;
        }

        public async Task<IActionResult> UserFiscalSetup()
        {
            var result = await _xenaService.GetUserFiscalSetupAsync();
            ViewBag.Json = result;
            return View("json");
        }

        public async Task<IActionResult> UserMembership()
        {
            var result = await _xenaService.GetUserMembershipAsync();
            ViewBag.Json = result;
            return View("json");
        }

        public async Task<IActionResult> UserApps()
        {
            // Get fiscal setup for current user
            var fiscalSetup = await _xenaService.GetUserFiscalSetupAsync();
            // Get fiscal ids from fiscal setup
            dynamic obj = JObject.Parse(fiscalSetup);
            var fiscalTasks = new List<Task<string>>();
            // Get each app data from xena api
            foreach (var entity in obj.Entities)
                fiscalTasks.Add(_xenaService.GetFiscalXenaAppsAsync(entity.Id.ToString()));
            await Task.WhenAll(fiscalTasks);
            ViewBag.Json = string.Join("****", fiscalTasks.Select(x => x.Result));
            return View("json");
        }
    }
}

ImplicitMVC.Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

ImplicitMVC.Core/Views/Home/Terms.cshtml
@{
    ViewData["Title"] = "Terms";
}

<h2>
    Terms of usage for your app
</h2>

ImplicitMVC.Core/Views/Shared/_Layout.cshtml
@using ImplicitMVC.Core.Extensions;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImplicitMVC.Core</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ImplicitMVC.Core</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Token" asp-action="Index">Token check</a></li>
                    </ul>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Xena <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-action="UserMembership" asp-controller="Xena">User MemberShip</a></li>
                            <li><a asp-action="UserFiscalSetup" asp-controller="Xena">User FiscalSetup</a></li>
                            <li><a asp-action="UserApps" asp-controller="Xena">User Apps</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-action="Logout" asp-controller="Home">Logout : @Context.User.GetPreferedDisplayName()</a></li>
                    }
                    else
                    {
                        <li><a asp-action="Login" asp-controller="Home">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ImplicitMVC.Core</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ImplicitMVC.Core/Views/Token/Index.cshtml
@using Microsoft.AspNetCore.Authentication

<h2>Claims</h2>

<dl>
    @foreach (var claim in User.Claims)
    {
        <dt>@claim.Type</dt>
        <dd>@claim.Value</dd>
    }
</dl>

<h2>Properties</h2>

<dl>
    @foreach (var prop in (await Context.AuthenticateAsync()).Properties.Items)
    {
        <dt>@prop.Key</dt>
        <dd>@prop.Value</dd>
    }
</dl>